version: "3.8" # Docker Compose file format version

services:
  mariadb:
    image: mariadb:10.5 # The official MariaDB image
    container_name: mariadb_container # Name of the container
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password # Set the root password for MariaDB
      - MYSQL_DATABASE=your_database_name # Optional: Define a default database
      - MYSQL_USER=your_user # Optional: Define a custom user
      - MYSQL_PASSWORD=your_user_password # Optional: Define the custom user's password
    ports:
      - "3306:3306" # Map the MariaDB port to the host machine's port 3306
    volumes:
      - ./ssl:/etc/mysql/certs # Mount the SSL certificate directory
    command: >
      mysqld
      --ssl-ca=/etc/mysql/certs/ca-cert.pem
      --ssl-cert=/etc/mysql/certs/server-cert.pem
      --ssl-key=/etc/mysql/certs/server-key.pem
